### ISSUE TITLE
TUI fails to open web app with external process

### ISSUE THREAD

**Issue by mdhaber** [MrShoenel/metrics-as-scores#6]
I [tried out the TUI](http://somup.com/c0nYY3yeeC). When I tried to run the web app as an external process, the GUI did not automatically show up in my browser. I tried browsing to `http://localhost:5678/webapp`, but the site couldn't be reached. When I quit, I saw an error:

```
An error (FileNotFoundError) has occurred: [WinError 2] The system cannot find the file specified

Restarting main menu.
```

What other information would you need to fix this?

**Comment by MrShoenel** [comment]
It is hard to say what actually happened there. I do think it is possible that this `FileNotFoundError` is actually related to a kind of handle, such as a Process-handle or Socket-handle. I think so because you reported that the GUI was not showing up. This happened because (most likely) the port was already in use, perhaps from an earlier unsuccessful launch (most likely from trying to use the internal server).

I have implemented a number of measures to improve the robustness of this and fixed some errors:

- Move the functionality to check the consistency of a local dataset into the helpers (out of the bundling workflow) and properly test it. The web server uses them prior to starting to check the selected dataset for consistency.
- There was a problem with the internal web application server: When shutting it down, it would also shut down the Asyncio loop that is needed for the TUI. I have improved the shutdown sequence of the internal webserver to not do that. However, it might still wait for the browser (tab) to close. Metrics As Scores checks now whether it is installed as a package or locally (cloned). If the former, the option to launch an internal web server is not shown any longer, as I deem this only useful when developing the application.
- Running the web application using an external process is now properly monitored and the communication with the sub-process is much improved: When starting the external process, its output is monitored for successful/erroneous launches. If successful, the browser is opened. Otherwise, the launch is canceled and a proper error message is given to the user (e.g., like an already in-use port).

In order to replicate the error you got, I tested two scenarios that did **not** yield the error any longer (using the latest `v2.3.3`):

Scenario 1: Install via PyPI
- Make a new empty directory, cd into it
- Create a new virtual environment (Python v3.10.6)
- `pip install metrics-as-scores`
- `mas`
- download the `diamonds-ideal-if` dataset, confirm it was not installed before and is installed after
- Launch the web server through an external process (only choice now when installed as a package), also loading the dataset into memory
    - Metrics As Scores now reports a successful launch of the process and then opens the web browser
    - When I choose an occupied port, Metrics As Scores reports an unsuccessful launch, and the user is presented with the main menu again


Scenario 2: Clone repo
- Clone repo into a new directory, cd into it
- Make a new virtual environment (`python -m venv venv`)
- `pip install poetry`, then `poetry install`
- `mas`
- download the same dataset, then test all constellations of internal/external, do and do not load into memory

**Comment by mdhaber** [comment]
Hmm, still not opening for me, and now the TUI freezes (or at least stops responding to input or CTRL+C).

**Comment by MrShoenel** [comment]
Thanks for reporting back!

1. Did you use the latest `v2.4.0` for testing? Did you use an installed package or a cloned repository?
2. Which dataset did you attempt to load?
3. Did you choose to load the entire dataset into memory? If so, did you see in the terminal that the server printed some messages about that?
4. What port did you use?
5. Did you ascertain that the port was not in use, prior to launching? If the server can launch successfully, it will print so in the terminal. It will also print if there was an error launching. Which message did you observe?

IIRC, you were using Windows. Assuming you use the default port `5678`, you can check whether it is in use like so:

1. Open a command prompt
2. Type `netstat -an | find "LISTEN" | find "5678"`

If the port is free, the output of this command should be empty.

Launching the external web server is equivalent to running the following command in the project root and the activated virtual environment (here using the dataset `iris` and pre-loading):

    bokeh serve src/metrics_as_scores/webapp --port=5678 --show --args dataset=iris preload

Could you try running this command and report back?

**Comment by mdhaber** [comment]
> Did you use the latest v2.4.0 for testing? 

I used the latest `master`; commit 91596585be211de46e897bfa18d449a6cb1434b7

> Did you use an installed package or a cloned repository?

Cloned repo.

> Which dataset did you attempt to load?

diamonds-ideal-if

> Did you choose to load the entire dataset into memory? If so, did you see in the terminal that the server printed some messages about that?

Tried both. No messages. 
![image](https://user-images.githubusercontent.com/6570539/221677343-a80062bb-c6fa-4d94-a227-7f16573bc6ea.png)

At this point it doesn't respond to input, and I have to close the terminal window.

> What port did you use?

The default.

> Did you ascertain that the port was not in use, prior to launching?

No.

> If the server can launch successfully, it will print so in the terminal. It will also print if there was an error launching. Which message did you observe?

Neither

> IIRC, you were using Windows. Assuming you use the default port 5678, you can check whether it is in use like so:
There is no output.

![image](https://user-images.githubusercontent.com/6570539/221677707-510afb82-a70b-4d80-8c26-96ab5cf5d576.png)

Could you try running this command and report back?

Before downloading the iris dataset, I got this. 

![image](https://user-images.githubusercontent.com/6570539/221678115-bb9b2176-3160-4b79-8553-74f027106dbb.png)

The web app opened. When I closed it, the terminal was unresponsive.

I'll try again after installing the dataset, but perhaps see if you can reproduce this issue on a Windows machine locally to debug.

*Update: that worked, but it still freezes the TUI. Same with the diamonds data set. Neither work via the TUI.*

**Comment by MrShoenel** [comment]
I believe it is resolved now. It appears that the subprocess can deadlock under Windows if it writes too much data.
That is why the browser opened in your case, while the TUI froze. It waited for a Semaphore that could never be acquired. The latest commits fix that behavior.

After choosing a dataset, you should always get some messages in the TUI now. Also, there was an unhandled exception block that should have re-raised. However, it was deadlocked by the Semaphore.

@ your last screenshot: That is the correct behavior. When calling the application with a dataset that cannot be loaded. I have now altered the behavior slightly to make the web server exit forcefully with a non-zero exit code in this case. When launching the web application externally, a premature crash will also be detected.

On a minor note: Some of the datasets were updated in the meantime. The web server should still launch without problems when using an older version though. The known datasets always point to the most recent version of a dataset.

**Comment by mdhaber** [comment]
After updating the iris dataset:

```
? Choose Method of Running the Web-App: Use External Process (works usually better)
? Would you like to pre-load the entire dataset into memory? Yes (Only recommended if you have enough memory)
? Enter a Port number: 5678
? Please choose one of the following Datasets: The Iris Flower Data Set [iris]

Cannot start the webserver: [WinError 2] The system cannot find the file specified: Traceback (most recent call last):
  File "C:\Users\matth\OneDrive\Desktop\metrics-as-scores\src\metrics_as_scores\cli\LocalWebserver.py", line 111, in start_server_process
    proc = Popen(args=args, cwd=str(root_dir.resolve()), stdout=PIPE, stderr=PIPE, env=my_env)
  File "C:\Users\matth\anaconda3\envs\mas\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\matth\anaconda3\envs\mas\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified



It was not possible to start the web application. Please read the error message and server log above. Most often, the port is already in use.

```
The port is not in use. (`netstat -an | find "LISTEN" | find "5678"` does not produce output.)

**Comment by MrShoenel** [comment]
It almost seems like it cannot find the `bokeh` executable in the environment. My wild guess is that this works somehow differently with `conda`.

I am creating the virtual environment like this:

    git clone https://github.com/MrShoenel/metrics-as-scores.git
    cd metrics-as-scores
    python -m venv venv # create virtual environment in cloned repo that is also called venv
    venv\Scripts\Activate # for Windows
    pip install poetry
    poetry install

Could you post the exact steps that you use with `conda`? Also, what version of `conda` are you using?

Another question: Does this problem also persist when you install Metrics As Scores as package?

**Comment by MrShoenel** [comment]
I do understand now why you encountered that bug. It is fixed in commit e20fbbe. The bug was caused by the assumption that the bokeh executable would be in the same directory as the python executable. When the environment and the working directory are disconnected (as is the case when using conda), that assumption does not hold. It is simplified now by just calling `bokeh`, which must be an executable on the path if Metrics As Scores was installed correctly. I tested running through conda, as package, locally, etc. and can confirm it works now. There is a new bugfix release `v2.4.2` that was made available on PyPI as well.

**Comment by MrShoenel** [comment]
@mdhaber were you able to test if the problem went away in the most recent release?

**Comment by mdhaber** [comment]
I tested it. Now when I exit, I get an infinite loop of "sleeping" printed to the screen.

![image](https://user-images.githubusercontent.com/6570539/224419448-f969f31e-802e-4b5e-be56-04426497eed5.png)

One thing that I would recommend (but will not track as an issue) is that it would be helpful if "Download and install a known or existing dataset" did not prompt the user to "Enter the ID of the dataset to download:". Instead, it could present a (condensed) list of options to select from. Currently, if the user has not already memorized the exact ID of the dataset, they need to exit the prompt (with ctrl+c?),  use "Show List of Known Datasets Available Online That Can Be Downloaded", and come back with the ID memorized, which is inconvenient.

Also, the graph in the web app would be improved if additional data would be calculated as necessary to account for the user zooming out of the plot. Additionally, for PDFs, CDFs, etc., the vertical axis does not need to show negative values.

![image](https://user-images.githubusercontent.com/6570539/224419020-1523ff03-1b61-4bf7-9e28-28c261902192.png)

**Comment by MrShoenel** [comment]
> I tested it. Now when I exit, I get an infinite loop of "sleeping" printed on the screen.

That was a (mostly) cosmetic error that is now fixed with 03689c3 and 71b64fb! But other than that, the local web server did work for you now? It opened the browser and presented the correct dataset? If so, I hope the issue can be closed :) Note I have not created another release, so you'll have to pull the repo if you intend to test more.


> One thing that I would recommend (but will not track as an issue) is that it would be helpful if "Download and install a known or existing dataset" did not prompt the user to "Enter the ID of the dataset to download:". Instead, it could present a (condensed) list of options to select from. Currently, if the user has not already memorized the exact ID of the dataset, they need to exit the prompt (with ctrl+c?), use "Show List of Known Datasets Available Online That Can Be Downloaded", and come back with the ID memorized, which is inconvenient.

Point taken, fixed in 5825c13 :)


> Also, the graph in the web app would be improved if additional data would be calculated as necessary to account for the user zooming out of the plot. Additionally, for PDFs, CDFs, etc., the vertical axis does not need to show negative values.

The short answer here is, that it works as intended. The long answer is much more elaborate, I'm afraid. The situation you have shown in the attached image is the result of zooming/panning, and the user is allowed to pan arbitrarily, such that I would not restrict the panning to only allow `y>=0`, for example, although that would make perfect sense for PDFs and (C)CDFs (not always for PPFs, however).

Metrics As Scores has a built-in mechanism to figure out the axes' ranges. For example, it knows that PDF's/CDF's do not require a negative `y`-axis, or that the domain for a PPF is `[0,1]`. In most situations, this gets applied automatically (for example, when switching from a PPF to a PDF). It can also be triggered by clicking the button 'Contain Plot'. It also has a mechanism to know the (approximate) range for `y`: when the densities for the web application were generated, it ran an optimization to find the largest mode.

About the additional data: The PDFs and CDFs show at least `99.5`% of the data. Internally, this is referred to as the `practical_domain`. The reason behind this is this: A parametric distribution may extend to $-\infty/\infty$ and even kernel density estimates can stretch far trying to accommodate all values. The result is that the plot would need to show a (too) large range on the `x`-axis. The practical domain is also determined when generating densities. It is then used in the web application to calculate all `y` values over this range. In other words, there is (practically) no additional data that could be calculated or shown, the curves that you see reflect at least `99.5`% of the complete curves.

There is also the checkbox 'Cut off smoothed distributions beyond observed values' that will restrict the density's domain to the range of observed values. This applies to "smoothed distributions", such as continuous parametric distributions and kernel density estimates, which may show a density `>0` beyond the observed values due to how they were fit.

**Comment by mdhaber** [comment]
I'm familiar with these things. The autoscaling to the practical domain/range is good. But my opinion remains that's the user experience would be improved if the code attempted to make sense of the user zooming out beyond the practical domain/range. I have specific suggestions, but I'll focus on the bugs for now.

I will try testing this again later.

**Comment by mdhaber** [comment]
With 5825c13145d20b6cad20ec9a19f6b2cda3545784, the TUI opens the web app as an external process whether I load all the data into memory or not. When I quit, I no longer see evidence of infinite loops, and I can quit everything cleanly. 

As a future improvement, I see that the server can detect "2023-03-11 10:21:00,520 WebSocket connection closed: code=1001, reason=None". Assuming that most users will use the server exactly once, perhaps that could automatically shut down the server so that the user does not need to enter "q" in the TUI.

**Comment by MrShoenel** [comment]
> With [5825c13](https://github.com/MrShoenel/metrics-as-scores/commit/5825c13145d20b6cad20ec9a19f6b2cda3545784), the TUI opens the web app as an external process whether I load all the data into memory or not. When I quit, I no longer see evidence of infinite loops, and I can quit everything cleanly.

Thanks for reporting back on this :)

> As a future improvement, I see that the server can detect "2023-03-11 10:21:00,520 WebSocket connection closed: code=1001, reason=None". Assuming that most users will use the server exactly once, perhaps that could automatically shut down the server so that the user does not need to enter "q" in the TUI.

I had been thinking about that, too. But it also happens that the browser might close and re-open the WebSocket connection, esp. when the tab loses focus or the browser is put into the background. So, unfortunately, it is not reliable enough.
